apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  namespace: kabanero
  name: appsody-hello-world
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: dnastacio/appsody-hello-world
            imagePullPolicy: Always
            ports:
            - containerPort: 9080
